from fastapi import APIRouter

from app.api.v1.endpoints import accounting, accounting_foundations, approvals, attachments, audit, auth, banking, cameras, customers, dashboard, divisions, email, expense_claims, fixed_assets, insights, intangible_assets, inter_account_transfers, inventory, invoices, jobs, locations, materials, pos, printers, products, quotes, rates, recurring_invoices, reports, sales, sales_channels, settlements, settings, statement_imports, statement_match_rules, supplies, tax

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(accounting.router)
api_router.include_router(cameras.router)
api_router.include_router(approvals.router)
api_router.include_router(audit.router)
api_router.include_router(settings.router)
api_router.include_router(materials.router)
api_router.include_router(supplies.router)
api_router.include_router(rates.router)
api_router.include_router(customers.router)
api_router.include_router(jobs.router)
api_router.include_router(printers.router)
api_router.include_router(products.router)
api_router.include_router(quotes.router)
api_router.include_router(invoices.router)
api_router.include_router(inventory.router)
api_router.include_router(sales_channels.router)
api_router.include_router(sales.router)
api_router.include_router(pos.router)
api_router.include_router(settlements.router)
api_router.include_router(reports.router)
api_router.include_router(dashboard.router)
api_router.include_router(insights.router)
api_router.include_router(tax.router)
api_router.include_router(email.router)
api_router.include_router(banking.router)
api_router.include_router(fixed_assets.router)
api_router.include_router(locations.router)
api_router.include_router(inter_account_transfers.router)
api_router.include_router(attachments.router)
api_router.include_router(recurring_invoices.router)
api_router.include_router(expense_claims.router)
api_router.include_router(intangible_assets.router)
api_router.include_router(statement_imports.router)
api_router.include_router(statement_match_rules.router)
api_router.include_router(accounting_foundations.router)
api_router.include_router(divisions.router)
